name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  animated_splash_screen: ^1.3.0
  flutter_glow: ^0.3.0
  

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/wind-day.json
    - assets/woman-enjoying-rain-day.json
    - assets/woman-taking-sunbath-on-beach.json
    - assets/maldives.jpg
    - assets/paris.jpg
    - assets/newyork.jpg
    - assets/berlin.jpg
    - assets/istanbul.jpg
    - assets/kreta.jpg
    - assets/pluvieux.png
    - assets/ciel.png
    - assets/soleil.png
    - assets/neige.png
